name: Go

on: push

jobs:

  build:
    name: Build
    runs-on: golang:1.19-buster
    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@v2

      - name: Build
        run: go build -v ./...

      - name: Test
        run: go test -v ./...
